import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

import Intro1 from '../components/Intro1.js';
import Intro2 from '../components/Intro2.js';
import Intro3 from '../components/Intro3.js';
import Intro4 from '../components/Intro4.js';
import Intro5 from '../components/Intro5.js';
import Intro6 from '../components/Intro6.js';
import Intro7 from '../components/Intro7.js';
import Footer from '../components/Footer.js';


import { FaChevronDown } from "react-icons/fa";


export default function Home() {
  return (
  <div>
    <div className="bg-black relative">
      <Head>
        <title>NFTRAFFICER | NFT Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="absolute z-50 w-full min-h-full">
        {/* header */}
          <div className="py-4">
            <div className="px-2 md:px-0 flex justify-center items-center">
              <Link href="/">
                <Image
                  src="/images/nftraffickerLogo.png"
                  height={90}
                  width={900}
                  className="cursor-pointer"
                />
              </Link>
            </div>
          </div>

          {/* menu */}
          <div className="w-full flex py-5 max-w-7xl mx-auto">
            <div className="px-6 transition duration-300 hover:scale-125">
              <Link href="/marketplace">
                <Image
                  src="/images/market.png"
                  height={70}
                  width={330}
                  className="cursor-pointer"
                />
              </Link>
            </div>
            <div className="px-6 transition duration-300 hover:scale-125">
              <Link href="/mint">
                <Image
                  src="/images/mint.png"
                  height={70}
                  width={200}
                  className="cursor-pointer"
                />
              </Link>
            </div>
            <div className="px-6 transition duration-300 hover:scale-125">
              <Link href="/collection">
                <Image
                  src="/images/collection.png"
                  height={70}
                  width={370}
                  className="cursor-pointer"
                />
              </Link>
            </div>
            <div className="px-6 transition duration-300 hover:scale-125">
              <Link href="/dashboard">
                <Image
                  src="/images/dashboard.png"
                  height={70}
                  width={370}
                  className="cursor-pointer"
                />
              </Link>
            </div>
          </div>

          {/* main */}
          <div className="flex flex-col md:flex-row h-96 px-6 py-5 max-w-7xl mx-auto justify-center items-center">
            <div className="w-full md:w-1/2">
              <h2 className="text-center md:text-left font-Poppins text-4xl text-white font-bold drop-shadow-lg">Your one stop shop<br /> for buying, selling and minting NFTs</h2>
            </div>
            <div className="w-1/2">
              <h1>NFTRAFFICER</h1>
            </div>
          </div>

          {/* scroll down */}
          <div className="flex px-6 py-5 max-w-7xl mx-auto justify-center items-center flex-col">
            <p>Scroll down to learn more</p>
            <FaChevronDown />
          </div>
        </div>


      <div className="w-full h-screen">
        {/* Background Image */}
        <Image
          src="/images/background.png"
          layout="fill"
          objectFit="cover"
        />
      </div>
    </div>

    {/* next section */}
    <div className="w-full bg-blue-300">
      <div className="w-full flex py-5 max-w-7xl mx-auto">
        <Intro1 />
      </div>
      <div className="w-full flex py-5 max-w-7xl mx-auto">
        <Intro2 />
      </div>
      <div className="w-full flex py-5 max-w-7xl mx-auto">
        <Intro3 />
      </div>
      <div className="w-full flex py-5 max-w-7xl mx-auto">
        <Intro4 />
      </div>
      <div className="w-full flex py-5 max-w-7xl mx-auto">
        <Intro5 />
      </div>
      <div className="w-full flex py-5 max-w-7xl mx-auto">
        <Intro6 />
      </div>
      <div className="w-full flex py-5 max-w-7xl mx-auto">
        <Intro7 />
      </div>
    </div>

    {/* footer */}
    <div className="w-full bg-pink-700">
      <div className="w-full flex pt-5 max-w-7xl mx-auto">
        <Footer />
      </div>
    </div>

  </div>
  )
}
