import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="bg-black relative">
      <Head>
        <title>NFTRAFFICER | NFT Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="absolute z-50 w-full">
      {/* header */}
        <div className="py-4">
          <div className="px-2 md:px-0 flex justify-center items-center">
            <Image
              src="/images/nftraffickerLogo.png"
              height={90}
              width={900}
            />
          </div>
        </div>
        {/* menu */}
        <div>
          <Link href="/marketplace">
            To Marketplace
          </Link>
        </div>
      </div>


      <div className="w-full h-screen">
        {/* Background Image */}
        <Image
          src="/images/background.png"
          layout="fill"
          objectFit="cover"
        />
      </div>
    </div>
  )
}
