import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="bg-black relative">
      <Head>
        <title>NFTRAFFICER | NFT Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="absolute z-50 w-full">
      
      {/* header */}
        <div className="py-4">
          <div className="px-2 md:px-0 flex justify-center items-center">
            <Link href="/">
              <Image
                src="/images/nftraffickerLogo.png"
                height={90}
                width={900}
                className="cursor-pointer"
              />
            </Link>
          </div>
        </div>

        {/* menu */}
        <div className="w-full flex py-5 max-w-7xl mx-auto">
          <div>
            <Link href="/marketplace">
              <Image
                src="/images/market.png"
                height={70}
                width={330}
                className="cursor-pointer"
              />
            </Link>
          </div>
          <div>
            <Link href="/mint">
              <Image
                src="/images/mint.png"
                height={70}
                width={330}
                className="cursor-pointer"
              />
            </Link>
          </div>
          <div>
            <Link href="/collection">
              <Image
                src="/images/collection.png"
                height={70}
                width={330}
                className="cursor-pointer"
              />
            </Link>
          </div>
          <div>
            <Link href="/dashboard">
              <Image
                src="/images/dashboard.png"
                height={70}
                width={330}
                className="cursor-pointer"
              />
            </Link>
          </div>
        </div>
      </div>


      <div className="w-full h-screen">
        {/* Background Image */}
        <Image
          src="/images/background.png"
          layout="fill"
          objectFit="cover"
        />
      </div>
    </div>
  )
}
