import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

import Footer from '../components/Footer.js';

export default function Home() {
  return (
  <div>
    <div className="bg-black relative">
      <Head>
        <title>Terms of Service | NFTRAFFICKER NFT Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="absolute z-50 w-full">

      {/* header */}
        <div className="py-4">
          <div className="px-2 md:px-0 flex justify-center items-center">
            <Link href="/">
              <Image
                src="/images/nftraffickerLogo.png"
                height={90}
                width={900}
                className="cursor-pointer"
              />
            </Link>
          </div>
        </div>

        {/* menu */}
        <div className="w-full flex py-5 max-w-7xl mx-auto">
          <div className="px-6 transition duration-300 hover:scale-125">
            <Link href="/marketplace">
              <Image
                src="/images/market.png"
                height={70}
                width={330}
                className="cursor-pointer"
              />
            </Link>
          </div>
          <div className="px-6 transition duration-300 hover:scale-125">
            <Link href="/mint">
              <Image
                src="/images/mint.png"
                height={70}
                width={200}
                className="cursor-pointer"
              />
            </Link>
          </div>
          <div className="px-6 transition duration-300 hover:scale-125">
            <Link href="/collection">
              <Image
                src="/images/collection.png"
                height={70}
                width={370}
                className="cursor-pointer"
              />
            </Link>
          </div>
          <div className="px-6 transition duration-300 hover:scale-125">
            <Link href="/dashboard">
              <Image
                src="/images/dashboard.png"
                height={70}
                width={370}
                className="cursor-pointer"
              />
            </Link>
          </div>
        </div>
        <div className="flex flex-col md:flex-row h-96 px-6 py-5 max-w-7xl mx-auto justify-center items-center">
          <div className="w-full md:w-2/3">
            <h2 className="text-center md:text-left font-Poppins text-4xl text-white font-bold drop-shadow-lg">Terms of Service</h2>
          </div>
          <div className="w-full md:w-1/3 p-2 drop-shadow-2xl">
            <div className="w-full border border-2 rounded-md border-zinc-700 p-4 bg-white">
              <p className="text-2xl font-bold font-Poppins pb-4">
                Terms of Service
              </p>
              <p className="text-2xl font-bold font-Poppins pb-4">
                Buy 'em now!'
              </p>
            </div>
          </div>
        </div>
      </div>


      <div className="w-full h-screen">
        {/* Background Image */}
        <Image
          src="/images/background.png"
          layout="fill"
          objectFit="cover"
        />
      </div>
    </div>

    {/* TERMS section */}
    <div className="w-full bg-blue-300">
      <div className="w-full flex py-5 max-w-7xl mx-auto">
        <div className="w-full p-2 drop-shadow-2xl">
          <div className="w-full border border-2 rounded-md border-zinc-700 p-4 bg-white">
            <h2 className="text-2xl font-bold pb-2 font-Poppins">1. Introduction</h2>
            <p className="text-xl font-Poppins pb-4">
              Welcome to Nftrafficker!, owned and operated by Sarif-Design, Nftrafficker! (“Nftrafficker!,” “we,” “us”, or “our”).
               These Terms of Service (“Terms”) govern your access to and use of the Nftrafficker! website(s),
               our APIs, mobile app (the “App”), and any other software, tools, features, or functionalities
               provided on or in connection with our services; including without limitation using our services
               to view, explore, and create NFTs and use our tools, at your own discretion, to connect directly
               with others to purchase, sell, or transfer NFTs on public blockchains (collectively, the “Service”).
               “NFT” in these Terms means a non-fungible token or similar digital item implemented on a
               blockchain (such as the Ethereum blockchain), which uses smart contracts to link to or
               otherwise be associated with certain content or data.
            </p>
            <p className="text-xl font-Poppins pb-4">
              For purposes of these Terms, “user”, “you”, and “your” means you as the user
              of the Service. If you use the Service on behalf of a company or other entity then
              “you” includes you and that entity, and you represent and warrant that (a) you are an
              authorized representative of the entity with the authority to bind the entity to these
              Terms, and (b) you agree to these Terms on the entity’s behalf.
            </p>
            <p className="text-xl font-Poppins pb-4">
              PLEASE READ THESE TERMS OF SERVICE CAREFULLY AS THEY CONTAIN IMPORTANT INFORMATION
              AND AFFECT YOUR LEGAL RIGHTS. AS OUTLINED IN SECTION 16 BELOW, THEY INCLUDE A MANDATORY
              ARBITRATION AGREEMENT AND CLASS ACTION WAIVER WHICH (WITH LIMITED EXCEPTIONS) REQUIRE
              ANY DISPUTES BETWEEN US TO BE RESOLVED THROUGH INDIVIDUAL ARBITRATION RATHER THAN BY A
              JUDGE OR JURY IN COURT.
            </p>
            <p className="text-xl font-Poppins pb-4">
              BY CLICKING TO ACCEPT AND/OR USING OUR SERVICE, YOU AGREE TO BE BOUND BY THESE
              TERMS AND ALL OF THE TERMS INCORPORATED HEREIN BY REFERENCE. IF YOU DO NOT AGREE
              TO THESE TERMS, YOU MAY NOT ACCESS OR USE THE SERVICE.
            </p>
            <p className="text-xl font-Poppins pb-4">
              Nftrafficker! is not a wallet provider, exchange, broker, financial institution, or creditor.
              Nftrafficker! provides a peer-to-peer web3 service that helps users discover and directly
              interact with each other and NFTs available on public blockchains. We do not have
              custody or control over the NFTs or blockchains you are interacting with and we do
              not execute or effectuate purchases, transfers, or sales of NFTs. To use our Service,
              you must use a third-party wallet which allows you to engage in transactions on blockchains.
            </p>
            <p className="text-xl font-Poppins pb-4">
              Nftrafficker! is not party to any agreement between any users.
              You bear full responsibility for verifying the identity, legitimacy,
              and authenticity of NFTs that you purchase from third-party sellers using
              the Service and we make no claims about the identity, legitimacy, functionality,
              or authenticity of users or NFTs (and any content associated with such NFTs)
              visible on the Service.
            </p>
            <p className="text-xl font-Poppins pb-4">
              Because we have a growing number of services, we sometimes need to provide additional
              terms for specific services (and such services are deemed part of the “Service”
              hereunder and shall also be subject to these Terms).
              Those additional terms and conditions, which are available
              with the relevant service, then become part of your agreement with us
              if you use those services. In the event of a conflict between these
              Terms and any additional applicable terms we may provide for a specific
              service, such additional terms shall control for that specific service.
            </p>
            <p className="text-xl font-Poppins pb-4">
              Nftrafficker! reserves the right to change or modify these Terms at any time and in our
              sole discretion. If we make material changes to these Terms, we will use reasonable
              efforts to provide notice of such changes, such as by providing notice through the
              Service or updating the “Last Updated” date at the beginning of these Terms.
              By continuing to access or use the Service, you confirm your acceptance of the
              revised Terms and all of the terms incorporated therein by reference effective
              as of the date these Terms are updated. It is your sole responsibility to review
              the Terms from time to time to view such changes and to ensure that you understand
              the terms and conditions that apply when you access or use the Service.
            </p>
          </div>
        </div>
      </div>

      <div className="w-full flex py-5 max-w-7xl mx-auto">
        <div className="w-full p-2 drop-shadow-2xl">
          <div className="w-full border border-2 rounded-md border-zinc-700 p-4 bg-white">
            <h2 className="text-2xl font-bold pb-2 font-Poppins">2. Accessing the Service</h2>
            <p className="text-xl font-Poppins pb-4">
              Like much of web3, your blockchain address functions as your identity on Nftrafficker!.
              Accordingly, you will need a blockchain address and a third-party wallet to access the
              Service. Your account on the service (“Account”) will be associated with your blockchain address.
            </p>
            <p className="text-xl font-Poppins pb-4">
              Your Account on Nftrafficker! will be associated with your linked blockchain address
              and display the NFTs for that blockchain address (and, if applicable, any content associated
              with such NFTs). By using your wallet in connection with the Service, you agree that you
              are using that wallet under the terms and conditions of the applicable provider of the wallet.
              Wallets are not operated by, maintained by, or affiliated with Nftrafficker!, and Nftrafficker! does not
              have custody or control over the contents of your wallet and has no ability to retrieve or transfer
              its contents. Nftrafficker! accepts no responsibility for, or liability to you, in connection with
              your use of a wallet and makes no representations or warranties regarding how the Service will
              operate with any specific wallet. You are solely responsible for keeping your wallet secure and
              you should never share your wallet credentials or seed phrase with anyone.
              If you discover an issue related to your wallet, please contact your wallet provider.
              Likewise, you are solely responsible for your Account and any associated wallet and we are
              not liable for any acts or omissions by you in connection with your Account or as a result
              of your Account or wallet being compromised. You agree to immediately notify us if you discover
              or otherwise suspect any security issues related to the Service or your Account.
            </p>
            <p className="text-xl font-Poppins pb-4">
              You also represent and warrant that you will comply with all applicable laws
              (e.g., local, state, federal and other laws) when using the Service.
              Without limiting the foregoing, by using the Service, you represent and warrant that:
              (a) you are not located in a country that is subject to a U.S. Government embargo;
              and (b) you have not been identified as a Specially Designated National or placed on any
              U.S. Government list of prohibited, sanctioned, or restricted parties.
              If you access or use the Service outside the United States, you are solely responsible for
              ensuring that your access and use of the Service in such country, territory or
              jurisdiction does not violate any applicable laws.
            </p>
            <p className="text-xl font-Poppins pb-4">
              Nftrafficker! may require you to provide additional information and documents in
              certain circumstances, such as at the request of any government authority,
              as any applicable law or regulation dictates, or to investigate a potential
              violation of these Terms. In such cases, Nftrafficker!, in its sole discretion,
              may disable your Account and block your ability to access the Service until such
              additional information and documents are processed by Nftrafficker!.
              If you do not provide complete and accurate information in response to such a
              request, Nftrafficker! may refuse to restore your access to the Service.
            </p>
            <p className="text-xl font-Poppins pb-4">
              Your access and use of the Service may be interrupted from time to time
              for any of several reasons, including, without limitation, the malfunction of
              equipment, periodic updating, maintenance, or repair of the Service or other
              actions that Nftrafficker!, in its sole discretion, may elect to take.
            </p>
            <p className="text-xl font-Poppins pb-4">
              We require all users to be at least 18 years old.
              If you are at least 13 years old but under 18 years old,
              you may only use Nftrafficker! through a parent or guardian’s
              Account and with their approval and oversight. That account holder is
              responsible for your actions using the Account. It is prohibited to use our
              Service if you are under 13 years old.
            </p>
          </div>
        </div>
      </div>

      <div className="w-full flex py-5 max-w-7xl mx-auto">
        <div className="w-full p-2 drop-shadow-2xl">
          <div className="w-full border border-2 rounded-md border-zinc-700 p-4 bg-white">
            <h2 className="text-2xl font-bold pb-2 font-Poppins">3. Ownership</h2>
            <p className="text-xl font-Poppins pb-4">
              The Service, including its “look and feel” (e.g., text, graphics, images, logos, page headers,
              button icons, and scripts), proprietary content, information and other materials, and
              all content and other materials contained therein, including, without limitation, the Nftrafficker!
              logo and all designs, text, graphics, pictures, data, software, sound files, other files, and
              the selection and arrangement thereof are the proprietary property of Nftrafficker! or our affiliates,
              licensors, or users, as applicable, and you agree not to take any action(s) inconsistent with
              such ownership interests. We and our affiliates, licensors, and users, as applicable,
              reserve all rights in connection with the Service and its content, including, without
              limitation, the exclusive right to create derivative works.
            </p>
            <p className="text-xl font-Poppins pb-4">
              Nftrafficker!’s name, logo, trademarks, and any Nftrafficker! product or service names,
              designs, logos, and slogans are the intellectual property of Nftrafficker! or our affiliates or
              licensors and may not be copied, imitated or used, in whole or in part, without our prior
              written permission in each instance. You may not use any metatags or other “hidden text”
              utilizing “Nftrafficker!” or any other name, trademark or product or service name of Nftrafficker!
              or our affiliates or licensors without our prior written permission. In addition, the
              “look and feel” of the Service constitutes the service mark, trademark or trade dress of Nftrafficker!
              and may not be copied, imitated or used, in whole or in part, without our prior written permission.
            </p>
            <p className="text-xl font-Poppins pb-4">
              All other third-party trademarks, registered trademarks, and product names
              mentioned on the Service or contained in the content linked to or associated
              with any NFTs displayed on the Service are the property of their respective
              owners and may not be copied, imitated or used, in whole or in part, without
              the permission of the applicable intellectual property rights holder. Reference
              to any products, services, processes or other information by name, trademark,
              manufacturer, supplier or otherwise does not constitute or imply endorsement,
              sponsorship, or recommendation by Nftrafficker!.
            </p>
            <p className="text-xl font-Poppins pb-4">
              We welcome feedback, comments, and suggestions for improvements to the Service (“Feedback”).
              You acknowledge and expressly agree that any contribution of Feedback does not and will not
              give or grant you any right, title, or interest in the Service or in any such Feedback.
              You agree that Nftrafficker! may use and disclose Feedback in any manner and for any
              purpose whatsoever without further notice or compensation to you and without
              retention by you of any proprietary or other right or claim. You hereby
              assign to Nftrafficker! any and all right, title, and interest
              (including, but not limited to, any patent, copyright, trade secret, trademark,
              show-how, know-how, moral rights and any and all other intellectual property right)
              that you may have in and to any and all Feedback.
            </p>
          </div>
        </div>
      </div>

      <div className="w-full flex py-5 max-w-7xl mx-auto">
        <div className="w-full p-2 drop-shadow-2xl">
          <div className="w-full border border-2 rounded-md border-zinc-700 p-4 bg-white">
            <h2 className="text-2xl font-bold pb-2 font-Poppins">4. License to Access and Use Our Service and Content</h2>
            <p className="text-xl font-Poppins pb-4">
              You are hereby granted a limited, nonexclusive, nontransferable, nonsublicensable,
              and personal license to access and use the Service provided, however, that such
              license is subject to your compliance with these Terms. If any software, content,
              or other materials owned by, controlled by, or licensed to us are distributed or
              made available to you as part of your use of the Service, we hereby grant you a non-
              commercial, personal, non-assignable, non-sublicensable, non-transferrable, and non-exclusive
              right and license to access and display such software, content, and materials provided
              to you as part of the Service (and right to download a single copy of the App onto your
              applicable equipment or device), in each case for the sole purpose of enabling you
              to use the Service as permitted by these Terms, provided that your license in any
              content linked to or associated with any NFTs is solely as set forth by the applicable
              seller or creator of such NFT.
            </p>
          </div>
        </div>
      </div>

      <div className="w-full flex py-5 max-w-7xl mx-auto">
        <div className="w-full p-2 drop-shadow-2xl">
          <div className="w-full border border-2 rounded-md border-zinc-700 p-4 bg-white">
            <h2 className="text-2xl font-bold pb-2 font-Poppins">5. Third-Party Content and Services</h2>
            <p className="text-xl font-Poppins pb-4">
              As a peer-to-peer web3 service, Nftrafficker! helps you explore NFTs created by third parties and
              interact with different blockchains. Nftrafficker! does not make any representations or
              warranties about this third-party content visible through our Service,
              including any content associated with NFTs displayed on the Service,
              and you bear responsibility for verifying the legitimacy, authenticity,
              and legality of NFTs that you purchase from third-party sellers.
              We also cannot guarantee that any NFTs visible on Nftrafficker! will always
              remain visible and/or available to be bought, sold, or transferred.
            </p>
            <p className="text-xl font-Poppins pb-4">
              NFTs may be subject to terms directly between buyers and sellers with respect to the
              use of the NFT content and benefits associated with a given NFT (“Purchase Terms”).
              For example, when you click to get more details about any of the NFTs visible on Nftrafficker!,
              you may notice a third party link to the creator’s website.
              Such website may include Purchase Terms governing the use of the
              NFT that you will be required to comply with. Nftrafficker! is not a party to any such
              Purchase Terms, which are solely between the buyer and the seller.
              The buyer and seller are entirely responsible for communicating,
              promulgating, agreeing to, and enforcing Purchase Terms. You are
              solely responsible for reviewing such Purchase Terms.
            </p>
            <p className="text-xl font-Poppins pb-4">
              The Service may also contain links or functionality to access or use third-party
              websites (“Third-Party Websites”) and applications (“Third-Party Applications”),
              or otherwise display, include, or make available content, data, information,
              services, applications, or materials from third parties (“Third-Party Materials”).
              When you click on a link to, or access and use, a Third-Party Website or Third-Party
              Application, though we may not warn you that you have left our Service, you are subject
              to the terms and conditions (including privacy policies) of another website or destination.
              Such Third-Party Websites, Third-Party Applications, and Third-Party Materials are not
              under the control of Nftrafficker!, and may be “open” applications for which no recourse
              is possible. Nftrafficker! is not responsible or liable for any Third-Party Websites,
              Third-Party Applications, and Third-Party Materials. Nftrafficker! provides links to
              these Third-Party Websites and Third-Party Applications only as a convenience and does
              not review, approve, monitor, endorse, warrant, or make any representations with
              respect to Third-Party Websites or Third-Party Applications, or their products or
              services or associated Third-Party Materials. You use all links in Third-Party
              Websites, Third-Party Applications, and Third-Party Materials at your own risk.
            </p>
          </div>
        </div>
      </div>

      <div className="w-full flex py-5 max-w-7xl mx-auto">
        <div className="w-full p-2 drop-shadow-2xl">
          <div className="w-full border border-2 rounded-md border-zinc-700 p-4 bg-white">
            <h2 className="text-2xl font-bold pb-2 font-Poppins">6. User Conduct</h2>
            <p className="text-xl font-Poppins pb-4">
              Openness is one of our most prized values, and we’re committed to providing
              people from all walks of life and varying experience levels with web3 with a
              colorful lens into different blockchains. However, to protect our community and
              comply with our legal obligations, we reserve the right to take action,
              with or without advance notice, if we believe you have violated these
              Terms. This may include: removing the ability to view certain NFTs on the
              Service or use our Service to interact with the NFTs; disabling the
              ability to use the Service in conjunction with buying/selling/transferring
              NFTs available on blockchains; disabling your ability to access our Service;
              and/or other actions.
            </p>
            <p className="text-xl font-Poppins pb-4">
              You agree that you will not violate any law, contract,
              intellectual property or other third-party right, and
              that you are solely responsible for your conduct and content,
              while accessing or using the Service. You also agree that you will not:
            </p>
            <ul className="pb-4">
              <li className="text-xl font-Poppins">- Use or attempt to use another user’s Account without authorization from such user;</li>
              <li className="text-xl font-Poppins">- Pose as another person or entity;</li>
              <li className="text-xl font-Poppins">- Claim an Nftrafficker! username for the purpose of reselling it or otherwise engage in name squatting;</li>
              <li className="text-xl font-Poppins">- Access the Service from a different blockchain address if we’ve blocked any of your other blockchain addresses from accessing the Service, unless you have our written permission first;</li>
              <li className="text-xl font-Poppins">- Distribute spam, including through sending unwanted NFTs to other users;</li>
              <li className="text-xl font-Poppins">- Use the Service – including through disseminating any software or interacting with any API – that could damage, disable, overburden, or impair the functioning of the Service in any manner;</li>
              <li className="text-xl font-Poppins">- Bypass or ignore instructions that control access to the Service, including attempting to circumvent any rate limiting systems by using multiple API keys, directing traffic through multiple IP addresses, or otherwise obfuscating the source of traffic you send to Nftrafficker!;</li>
              <li className="text-xl font-Poppins">- Use any data mining, robot, spider, crawler, scraper, script, browser extension, offline reader, or other automated means or interface not authorized by us to access the Service, extract data, or otherwise interfere with or modify the rendering of Service pages or functionality;</li>
              <li className="text-xl font-Poppins">- Reverse engineer, duplicate, decompile, disassemble, or decode any aspect of the Service, or do anything that might discover source code or bypass or circumvent measures employed to prevent or limit access to any service, area, or code of the Service;</li>
              <li className="text-xl font-Poppins">- Sell or resell the Service or attempt to circumvent any Nftrafficker! fee systems;</li>
              <li className="text-xl font-Poppins">- Engage in behaviors that have the intention or the effect of artificially causing an item or collection to appear at the top of search results, or artificially increasing view counts, favorites, or other metrics that Nftrafficker! might use to sort search results;</li>
              <li className="text-xl font-Poppins">- Use the Service or data collected from our Service for any advertising or direct marketing activity (including without limitation, email marketing, SMS marketing, and telemarketing);</li>
              <li className="text-xl font-Poppins">- Use the Service for money laundering, terrorist financing, or other illicit finance;</li>
              <li className="text-xl font-Poppins">- Use the Service from a country sanctioned by the government of the United States or to facilitate transactions involving individuals sanctioned by the government of the United States or located in sanctioned countries;</li>
              <li className="text-xl font-Poppins">- Use the Service to carry out any financial activities subject to registration or licensing, including but not limited to creating, selling, or buying securities, commodities, options, or debt instruments;</li>
              <li className="text-xl font-Poppins">- Use the Service to create, sell, or buy NFTs or other items that give owners rights to participate in an ICO or any securities offering, or that are redeemable for securities, commodities, or other financial instruments;</li>
              <li className="text-xl font-Poppins">- Use the Service to engage in price manipulation, fraud, or other deceptive, misleading, or manipulative activity;</li>
              <li className="text-xl font-Poppins">- Use the Service to buy, sell, or transfer stolen items, fraudulently obtained items, items taken without authorization, and/or any other illegally obtained items;</li>
              <li className="text-xl font-Poppins">- Infringe or violate the intellectual property rights or any other rights of others;</li>
              <li className="text-xl font-Poppins">- Create or display illegal content, such as content that may involve child sexual exploitation;</li>
              <li className="text-xl font-Poppins">- Create or display NFTs or other items that promote suicide or self-harm, incites hate or violence against others, or doxes another individual;</li>
              <li className="text-xl font-Poppins">- Use the Service for any illegal or unauthorized purpose, including creating or displaying illegal content, such as content that may involve child sexual exploitation, or encouraging or promoting any activity that violates the Terms of Service;</li>
              <li className="text-xl font-Poppins">- Use the Service in any manner that could interfere with, disrupt, negatively affect or inhibit other users from fully enjoying the Service.</li>
            </ul>
            <p className="text-xl font-Poppins pb-4">
              We allow users to post NSFW content, but that content and other associated material is subject to being marked NSFW and may be handled differently than non-NSFW content in navigation menus and search results.
            </p>
            <p className="text-xl font-Poppins pb-4">
              Finally, by using the Service, you understand the importance of DYOR – doing your own research. You bear full responsibility for verifying the authenticity, legitimacy, identity, and other details about any NFT, collection, or account that you view or otherwise interact with in conjunction with our Service. We make no guarantees or promises about the identity, legitimacy, or authenticity of any NFT, collection, or account on the Service.
            </p>
          </div>
        </div>
      </div>

      <div className="w-full flex py-5 max-w-7xl mx-auto">
        <div className="w-full p-2 drop-shadow-2xl">
          <div className="w-full border border-2 rounded-md border-zinc-700 p-4 bg-white">
            <h2 className="text-2xl font-bold pb-2 font-Poppins">7. Intellectual Property Rights</h2>
            <p className="text-xl font-Poppins pb-4">
              You are solely responsible for your use of the Service and for any information you provide, including compliance with applicable laws, rules, and regulations, as well as these Terms, including the User Conduct requirements outlined above.
            </p>
            <p className="text-xl font-Poppins pb-4">
              By using the Service in conjunction with creating, submitting, posting,
              promoting, or displaying content, or by complying with Nftrafficker!’s metadata standards
              in your metadata API responses, you grant us a worldwide, non-exclusive, sublicensable,
              royalty-free license to use, copy, modify, and display any content, including but
              not limited to text, materials, images, files, communications, comments, feedback,
              suggestions, ideas, concepts, questions, data, or otherwise, that you submit or post
              on or through the Service for our current and future business purposes, including to
              provide, promote, and improve the Service. This includes any digital file, art,
              or other material linked to or associated with any NFTs that are displayed on the
              Service.
            </p>
            <p className="text-xl font-Poppins pb-4">
              Nftrafficker! does not claim that submitting, posting, or displaying this content
              on or through the Service gives Nftrafficker! any ownership of the content.
              We're not saying we own it. We're just saying we might use it and show
              it off a bit.
            </p>
            <p className="text-xl font-Poppins pb-4">
              You represent and warrant that you have, or have obtained, all rights,
              licenses, consents, permissions, power and/or authority necessary to
              grant the rights granted herein for any content that you create, submit, post,
              promote, or display on or through the Service. You represent and warrant that
              such content does not contain material subject to copyright, trademark, publicity
              rights, or other intellectual property rights, unless you have necessary permission
              or are otherwise legally entitled to post the material and to grant Nftrafficker! the
              license described above, and that the content does not violate any laws.
            </p>
          </div>
        </div>
      </div>

      <div className="w-full flex py-5 max-w-7xl mx-auto">
        <div className="w-full p-2 drop-shadow-2xl">
          <div className="w-full border border-2 rounded-md border-zinc-700 p-4 bg-white">
            <h2 className="text-2xl font-bold pb-2 font-Poppins">8. Indemnification</h2>
            <p className="text-xl font-Poppins pb-4">
              By agreeing to these Terms and accessing the Service, you agree, to the fullest extent
              permitted by applicable law, to indemnify, defend, and hold harmless Nftrafficker!,
              and our respective past, present, and future employees, officers, directors, contractors,
              consultants, equity holders, suppliers, vendors, service providers, parent companies,
              subsidiaries, affiliates, agents, representatives, predecessors, successors, and assigns
              (individually and collectively, the “Nftrafficker! Parties”), from and against all actual or
              alleged claims, damages, awards, judgments, losses, liabilities, obligations, penalties,
              interest, fees, expenses (including, without limitation, attorneys’ fees and expenses),
              and costs (including, without limitation, court costs, costs of settlement, and costs of
              pursuing indemnification and insurance), of every kind and nature whatsoever, whether
              known or unknown, foreseen or unforeseen, matured or unmatured, or suspected or
              unsuspected, in law or equity, whether in tort, contract, or otherwise (collectively,
              “Claims”), including, but not limited to, damages to property or personal injury,
              that are caused by, arise out of or are related to (a) your use or misuse of the
              Service, content, NFTs, or content linked to or associated with any NFTs (b) any
              Feedback you provide, (c) your violation or breach of any term of these Terms or
              applicable law, and (d) your violation of the rights of or obligations to a third
              party, including another user or third-party, and (e) your negligence or wilful misconduct.
              You agree to promptly notify Nftrafficker! of any Claims and cooperate with the Nftrafficker!
              Parties in defending such Claims. You further agree that the Nftrafficker!
              Parties shall have control of the defense or settlement of any Claims.
              THIS INDEMNITY IS IN ADDITION TO, AND NOT IN LIEU OF, ANY OTHER INDEMNITIES
              SET FORTH IN A WRITTEN AGREEMENT BETWEEN YOU AND NFTRAFFICKER!.
            </p>
          </div>
        </div>
      </div>

      <div className="w-full flex py-5 max-w-7xl mx-auto">
        <div className="w-full p-2 drop-shadow-2xl">
          <div className="w-full border border-2 rounded-md border-zinc-700 p-4 bg-white">
            <h2 className="text-2xl font-bold pb-2 font-Poppins">9. Disclaimers</h2>
            <p className="text-xl font-Poppins pb-4">
              YOUR ACCESS TO AND USE OF THE SERVICE IS AT YOUR OWN RISK. YOU UNDERSTAND AND
              AGREE THAT THE SERVICE IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS AND NFTRAFFICKER!
              EXPRESSLY DISCLAIMS WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED. NFTRAFFICKER!
              (AND ITS SUPPLIERS) MAKE NO WARRANTY OR REPRESENTATION AND DISCLAIM ALL RESPONSIBILITY FOR
              WHETHER THE SERVICE: (A) WILL MEET YOUR REQUIREMENTS; (B) WILL BE AVAILABLE ON AN UNINTERRUPTED,
              TIMELY, SECURE, OR ERROR-FREE BASIS; OR (C) WILL BE ACCURATE, RELIABLE, COMPLETE, LEGAL, OR
              SAFE. NFTRAFFICKER! DISCLAIMS ALL OTHER WARRANTIES OR CONDITIONS, EXPRESS OR IMPLIED, INCLUDING,
              WITHOUT LIMITATION, IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A
              PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. NFTRAFFICKER! WILL NOT BE LIABLE FOR ANY LOSS OF
              ANY KIND FROM ANY ACTION TAKEN OR TAKEN IN RELIANCE ON MATERIAL OR INFORMATION, CONTAINED
              ON THE SERVICE. WHILE NFTRAFFICKER! ATTEMPTS TO MAKE YOUR ACCESS TO AND USE OF THE SERVICE SAFE,
              NFTRAFFICKER! CANNOT AND DOES NOT REPRESENT OR WARRANT THAT THE SERVICE, CONTENT, CONTENT
              LINKED TO OR ASSOCIATED WITH ANY NFTS, OR ANY NFTS YOU INTERACT WITH USING OUR SERVICE
              OR OUR SERVICE PROVIDERS’ SERVERS ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.
              WE CANNOT GUARANTEE THE SECURITY OF ANY DATA THAT YOU DISCLOSE ONLINE. NO ADVICE OR
              INFORMATION, WHETHER ORAL OR OBTAINED FROM THE NFTRAFFICKER! PARTIES OR THROUGH THE SERVICE,
              WILL CREATE ANY WARRANTY OR REPRESENTATION NOT EXPRESSLY MADE HEREIN. YOU ACCEPT THE
              INHERENT SECURITY RISKS OF PROVIDING INFORMATION AND DEALING ONLINE OVER THE INTERNET
              AND WILL NOT HOLD NFTRAFFICKER! RESPONSIBLE FOR ANY BREACH OF SECURITY.
            </p>
            <p className="text-xl font-Poppins pb-4">
              WE WILL NOT BE RESPONSIBLE OR LIABLE TO YOU FOR ANY LOSS AND TAKE NO
              RESPONSIBILITY FOR, AND WILL NOT BE LIABLE TO YOU FOR, ANY USE OF NFTS,
              CONTENT, AND/OR CONTENT LINKED TO OR ASSOCIATED WITH NFTS, INCLUDING BUT
              NOT LIMITED TO ANY LOSSES, DAMAGES, OR CLAIMS ARISING FROM: (A) USER ERROR,
              INCORRECTLY CONSTRUCTED TRANSACTIONS, OR MISTYPED ADDRESSES; (B) SERVER
              FAILURE OR DATA LOSS; (C) UNAUTHORIZED ACCESS OR USE; (D) ANY UNAUTHORIZED
              THIRD-PARTY ACTIVITIES, INCLUDING WITHOUT LIMITATION THE USE OF VIRUSES,
              PHISHING, BRUTEFORCING OR OTHER MEANS OF ATTACK AGAINST THE SERVICE OR NFTS.
            </p>
            <p className="text-xl font-Poppins pb-4">
              NFTS EXIST ONLY BY VIRTUE OF THE OWNERSHIP RECORD MAINTAINED IN THE
              ASSOCIATED BLOCKCHAIN (E.G., ETHEREUM NETWORK). ANY TRANSFERS OR
              SALES OCCUR ON THE ASSOCIATED BLOCKCHAIN (E.G., ETHEREUM). NFTRAFFICKER! AND/OR
              ANY OTHER NFTRAFFICKER! PARTY CANNOT EFFECT OR OTHERWISE CONTROL THE TRANSFER OF
              TITLE OR RIGHT IN ANY NFTS OR UNDERLYING OR ASSOCIATED CONTENT OR ITEMS.
            </p>
            <p className="text-xl font-Poppins pb-4">
              NO NFTRAFFICKER! PARTY IS RESPONSIBLE OR LIABLE FOR ANY SUSTAINED LOSSES OR
              INJURY DUE TO VULNERABILITY OR ANY KIND OF FAILURE, ABNORMAL
              BEHAVIOR OF SOFTWARE (E.G., WALLET, SMART CONTRACT), BLOCKCHAINS OR
              ANY OTHER FEATURES OF THE NFTS. NO NFTRAFFICKER!
              PARTY IS RESPONSIBLE FOR LOSSES OR INJURY DUE TO LATE REPORTS BY
              DEVELOPERS OR REPRESENTATIVES (OR NO REPORT AT ALL) OF ANY
              ISSUES WITH THE BLOCKCHAIN SUPPORTING THE NFTS, INCLUDING FORKS,
              TECHNICAL NODE ISSUES OR ANY OTHER ISSUES HAVING LOSSES OR INJURY
              AS A RESULT.
            </p>
          </div>
        </div>
      </div>

      <div className="w-full flex py-5 max-w-7xl mx-auto">
        <div className="w-full p-2 drop-shadow-2xl">
          <div className="w-full border border-2 rounded-md border-zinc-700 p-4 bg-white">
            <h2 className="text-2xl font-bold pb-2 font-Poppins">10. Assumption of Risk</h2>
            <p className="text-xl font-Poppins pb-4">
              You accept and acknowledge:
            </p>
            <ul className="pb-4">
              <li className="text-xl font-Poppins">- The value of an NFTs is subjective. Prices of NFTs are subject to volatility and fluctuations in the price of cryptocurrency can also materially and adversely affect NFT prices. You acknowledge that you fully understand this subjectivity and volatility and that you may lose money.</li>
              <li className="text-xl font-Poppins">- A lack of use or public interest in the creation and development of distributed ecosystems could negatively impact the development of those ecosystems and related applications, and could therefore also negatively impact the potential utility of NFTs.</li>
              <li className="text-xl font-Poppins">- The regulatory regime governing blockchain technologies, non-fungible tokens, cryptocurrency, and other crypto-based items is uncertain, and new regulations or policies may materially adversely affect the development of the Service and the utility of NFTs.</li>
              <li className="text-xl font-Poppins">- You are solely responsible for determining what, if any, taxes apply to your transactions. Nftrafficker! is not responsible for determining the taxes that apply to your NFTs.</li>
              <li className="text-xl font-Poppins">- There are risks associated with purchasing items associated with content created by third parties through peer-to-peer transactions, including but not limited to, the risk of purchasing counterfeit items, mislabeled items, items that are vulnerable to metadata decay, items on smart contracts with bugs, and items that may become untransferable. You represent and warrant that you have done sufficient research before making any decisions to sell, obtain, transfer, or otherwise interact with any NFTs or accounts/collections.</li>
              <li className="text-xl font-Poppins">- We do not control the public blockchains that you are interacting with and we do not control certain smart contracts and protocols that may be integral to your ability to complete transactions on these public blockchains. Additionally, blockchain transactions are irreversible and Nftrafficker! has no ability to reverse any transactions on the blockchain.</li>
              <li className="text-xl font-Poppins">- There are risks associated with using Internet and blockchain based products, including, but not limited to, the risk associated with hardware, software, and Internet connections, the risk of malicious software introduction, and the risk that third parties may obtain unauthorized access to your third-party wallet or Account. You accept and acknowledge that Nftrafficker! will not be responsible for any communication failures, disruptions, errors, distortions or delays you may experience when using the Service or any Blockchain network, however caused.</li>
              <li className="text-xl font-Poppins">- The Service relies on third-party platforms and/or vendors. If we are unable to maintain a good relationship with such platform providers and/or vendors; if the terms and conditions or pricing of such platform providers and/or vendors change; if we violate or cannot comply with the terms and conditions of such platforms and/or vendors; or if any of such platforms and/or vendors loses market share or falls out of favor or is unavailable for a prolonged period of time, access to and use of the Service will suffer.</li>
              <li className="text-xl font-Poppins">- Nftrafficker! reserves the right to hide collections, contracts, and items affected by any of these issues or by other issues. Items you purchase may become inaccessible on Nftrafficker!. Under no circumstances shall the inability to view items on Nftrafficker! or an inability to use the Service in conjunction with the purchase, sale, or transfer of items available on any blockchains serve as grounds for a claim against Nftrafficker!.</li>
              <li className="text-xl font-Poppins">- If you have a dispute with one or more users, YOU RELEASE US FROM CLAIMS, DEMANDS, AND DAMAGES OF EVERY KIND AND NATURE, KNOWN AND UNKNOWN, ARISING OUT OF OR IN ANY WAY CONNECTED WITH SUCH DISPUTES. IN ENTERING INTO THIS RELEASE YOU EXPRESSLY WAIVE ANY PROTECTIONS (WHETHER STATUTORY OR OTHERWISE) THAT WOULD OTHERWISE LIMIT THE COVERAGE OF THIS RELEASE TO INCLUDE THOSE CLAIMS WHICH YOU MAY KNOW OR SUSPECT TO EXIST IN YOUR FAVOR AT THE TIME OF AGREEING TO THIS RELEASE.</li>
            </ul>
          </div>
        </div>
      </div>

      <div className="w-full flex py-5 max-w-7xl mx-auto">
        <div className="w-full p-2 drop-shadow-2xl">
          <div className="w-full border border-2 rounded-md border-zinc-700 p-4 bg-white">
            <h2 className="text-2xl font-bold pb-2 font-Poppins">11. Limitation of Liability</h2>
            <p className="text-xl font-Poppins pb-4">
              TO THE FULLEST EXTENT PERMITTED BY LAW, YOU AGREE THAT IN NO EVENT WILL NFTRAFFICKER! OR ITS SERVICE PROVIDERS BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY LOST PROFIT OR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL, OR PUNITIVE DAMAGES ARISING FROM THESE TERMS OR THE SERVICE, PRODUCTS OR THIRD-PARTY SITES AND PRODUCTS, OR FOR ANY DAMAGES RELATED TO LOSS OF REVENUE, LOSS OF PROFITS, LOSS OF BUSINESS OR ANTICIPATED SAVINGS, LOSS OF USE, LOSS OF GOODWILL, OR LOSS OF DATA, AND WHETHER CAUSED BY STRICT LIABILITY OR TORT (INCLUDING NEGLIGENCE), BREACH OF CONTRACT, OR OTHERWISE, EVEN IF FORESEEABLE AND EVEN IF NFTRAFFICKER! OR ITS SERVICE PROVIDERS HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (B) FOR ANY OTHER CLAIM, DEMAND, OR DAMAGES WHATSOEVER RESULTING FROM OR ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OF THE DELIVERY, USE, OR PERFORMANCE OF THE SERVICE. ACCESS TO, AND USE OF, THE SERVICE, PRODUCTS OR THIRD-PARTY SITES, AND PRODUCTS ARE AT YOUR OWN DISCRETION AND RISK, AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR MOBILE DEVICE OR LOSS OF DATA RESULTING THEREFROM.
            </p>
            <p className="text-xl font-Poppins pb-4">
              NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, IN NO EVENT SHALL THE MAXIMUM AGGREGATE LIABILITY OF NFTRAFFICKER! ARISING OUT OF OR IN ANY WAY RELATED TO THESE TERMS, THE ACCESS TO AND USE OF THE SERVICE, CONTENT, NFTS, OR ANY NFTRAFFICKER! PRODUCTS OR SERVICES EXCEED THE GREATER OF (A) $100 OR (B) THE AMOUNT RECEIVED BY NFTRAFFICKER! FOR ITS SERVICE DIRECTLY RELATING TO THE ITEMS THAT ARE THE SUBJECT OF THE CLAIM. THE FOREGOING LIMITATIONS WILL APPLY EVEN IF THE ABOVE STATED REMEDY FAILS OF ITS ESSENTIAL PURPOSE.
            </p>
            <p className="text-xl font-Poppins pb-4">
              Some jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you. Some jurisdictions also limit disclaimers or limitations of liability for personal injury from consumer products, so this limitation may not apply to personal injury claims.
            </p>
          </div>
        </div>
      </div>

      <div className="w-full flex py-5 max-w-7xl mx-auto">
        <div className="w-full p-2 drop-shadow-2xl">
          <div className="w-full border border-2 rounded-md border-zinc-700 p-4 bg-white">
            <h2 className="text-2xl font-bold pb-2 font-Poppins">12. Privacy Policy</h2>
            <p className="text-xl font-Poppins pb-4">
              Please refer to our <Link href="/privacy"><span className="text-pink-700 transition duration-300 hover:text-yellow-500 cursor-pointer">Privacy Policy</span></Link> for information about how we collect, use, and share personal data about you. By
              submitting personal data through our Service, you agree to the terms of our <Link href="/privacy"><span className="text-pink-700 transition duration-300 hover:text-yellow-500 cursor-pointer">Privacy Policy</span></Link> and you expressly
              consent to the collection, use, and disclosure of your personal data in accordance
              with the <Link href="/privacy"><span className="text-pink-700 transition duration-300 hover:text-yellow-500 cursor-pointer">Privacy Policy</span></Link>.
            </p>
          </div>
        </div>
      </div>

      <div className="w-full flex pt-5 pb-10 max-w-7xl mx-auto">
        <div className="w-full p-2 drop-shadow-2xl">
          <div className="w-full border border-2 rounded-md border-zinc-700 p-4 bg-white">
            <h2 className="text-2xl font-bold pb-2 font-Poppins">13. Modifications to the Service</h2>
            <p className="text-xl font-Poppins pb-4">
              We reserve the right in our sole discretion to modify, suspend, or discontinue, temporarily or permanently, the Service (or any features or parts thereof) at any time and without liability as a result.
            </p>
          </div>
        </div>
      </div>

    </div>

    {/* footer */}
    <div className="w-full bg-pink-700">
      <div className="w-full flex pt-5 max-w-7xl mx-auto">
        <Footer />
      </div>
    </div>
  </div>
  )
}
